name: Trigger Docs Submodule Update

on:
  push:
    branches:
      - main

jobs:
  trigger-update:
    runs-on: ubuntu-latest
    steps:
    - name: Trigger Repository Dispatch in Docs Repository
      run: |
        curl -X POST \
          -H "Authorization: token ${{ secrets.KEY_CLEMENT_SUBMODULE }}" \
          -H "Accept: application/vnd.github.v3+json" \
          https://api.github.com/repos/mistralai/platform-docs/dispatches \
          -d '{"event_type":"update-submodule-request"}'